# Generated by Django 3.2.25 on 2024-05-16 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='number',
            field=models.CharField(default='', max_length=20, unique=True),
        ),
    ]
