# Generated by Django 3.2.25 on 2024-05-28 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_alter_user_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile',
            field=models.ImageField(default='profile/person.svg', null=True, upload_to='profile/'),
        ),
    ]
