# Generated by Django 3.2.25 on 2024-04-04 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DS', '0003_comment_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=10)),
            ],
        ),
    ]
