# Generated by Django 3.2.25 on 2024-04-04 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DS', '0005_project_years'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='years',
            new_name='year',
        ),
    ]
