# Generated by Django 3.2.25 on 2024-05-05 10:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('DS', '0008_project_imgfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='uploadedFile',
            field=models.FileField(blank=True, null=True, upload_to='zipfile/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='harts',
            field=models.ManyToManyField(blank=True, null=True, related_name='hart_project', to=settings.AUTH_USER_MODEL),
        ),
    ]
