# Generated by Django 3.2.25 on 2024-05-05 10:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('DS', '0009_auto_20240505_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='harts',
            field=models.ManyToManyField(related_name='hart_project', to=settings.AUTH_USER_MODEL),
        ),
    ]
