# Generated by Django 3.2.25 on 2024-05-05 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DS', '0010_alter_project_harts'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='abstract',
            field=models.CharField(default='안녕', max_length=200),
            preserve_default=False,
        ),
    ]
