# Generated by Django 3.2.25 on 2024-05-06 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DS', '0011_project_abstract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='abstract',
            field=models.CharField(max_length=100),
        ),
    ]
