# Generated by Django 3.2.25 on 2024-05-16 12:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('DS', '0013_auto_20240516_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='harts',
            field=models.ManyToManyField(blank=True, related_name='hart_project', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='hashtag',
            field=models.ManyToManyField(blank=True, related_name='project_hashtag', to='DS.Hashtag'),
        ),
    ]
