# Generated by Django 3.2.25 on 2024-05-23 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DS', '0015_auto_20240523_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='oldproj',
            name='uploadedFile',
            field=models.FileField(blank=True, null=True, upload_to='zipfile/'),
        ),
    ]
