# Generated by Django 3.2.25 on 2024-05-23 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DS', '0016_oldproj_uploadedfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='abstract',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.DeleteModel(
            name='OldProj',
        ),
    ]
