# Generated by Django 3.2.25 on 2024-05-28 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DS', '0018_auto_20240523_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='abstract',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='content',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='project',
            name='poster',
            field=models.FileField(null=True, upload_to='paperfile/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='repoter',
            field=models.FileField(null=True, upload_to='repoter/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='uploadedFile',
            field=models.FileField(null=True, upload_to='zipfile/'),
        ),
    ]
